# Generated by Django 6.0.2 on 2026-02-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='quantite',
            field=models.PositiveIntegerField(default=1, verbose_name="Nombre d'exemplaires"),
        ),
    ]
